### ISSUE TITLE
Doesn't work with LNPopupController library

### ISSUE THREAD

**Issue by rastaman111** [iDevelopper/PBMediaSlider#1]
Hello!
PBMediaSlider does not work when the screen is presented via the LNPopupController library, although if you show the screen as a system "present(vc)" then everything works fine

Attached a video and a test project

https://github.com/user-attachments/assets/14e8320a-9a02-4db0-b3ac-889546e9e037

[TestSlider.zip](https://github.com/user-attachments/files/16679801/TestSlider.zip)

**Comment by iDevelopper** [comment]
Hello,

Sorry for the late reply, I was on vacation and away!

I guess it's a conflict with the gesture recognizer of LNPopupController.

I'll check it out.

**Comment by rastaman111** [comment]
Hi 
I inserted this code into the slider file and it worked, but i'm not sure if it's the best solution

    public override func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        return false
    }

**Comment by iDevelopper** [comment]
Yes, that's it! I will update the library.

https://developer.apple.com/documentation/uikit/uiview/1622460-gesturerecognizershouldbegin/

"Subclasses may override this method and use it to prevent the recognition of particular gestures. For example, the [UISlider](https://developer.apple.com/documentation/uikit/uislider) class uses this method to prevent swipes parallel to the slider’s travel direction and that start in the thumb.

At the time this method is called, the gesture recognizer is in the UIGestureRecognizer.State.possible state and thinks it has the events needed to move to the [UIGestureRecognizer.State.began](https://developer.apple.com/documentation/uikit/uigesturerecognizer/state/began) state.

The default implementation of this method returns true."

**Comment by iDevelopper** [comment]
Thanks for reporting this!

Can you update your package to 0.1.1 and check?

**Comment by rastaman111** [comment]
yes I'm sure about this code, I tested it while you were answering ;)
